/**
 * Generated by scripts/build.mjs. Do not edit — edit src/host/index.js.
 *
 * The host half lives in ./host/ so that each collaborator is its own module;
 * this file exists because `main` and the `exports` map point at lib/index.js.
 */
export { apply, name, inject } from './host/index.js'
