/**
 * build.mjs — the whole build, in Node, with no bash.
 *
 * The previous build was `bash scripts/build.sh`, which cannot run on a Windows
 * checkout without Git Bash — the maintainer's machine included. This does the
 * same three jobs and works anywhere Node does:
 *
 *   1. host half   copy src/host/*.js -> lib/host/*.js and src/host/index.js ->
 *                  lib/index.js (plain JS, no compiler, relative ESM imports)
 *   2. built-ins   node scripts/embed-clips.mjs regenerates clips.meta/data.js
 *   3. client half tsdown bundles src/client/** into lib/client.js
 *
 * It also PRUNES lib/host of files whose source is gone. A stale module left in
 * lib/ would still be importable, so a deleted file could look alive after a
 * build — the kind of divergence `npm run verify:build` exists to catch.
 *
 * Usage: node scripts/build.mjs [--skip-embed] [--skip-client]
 */
import { execFileSync } from 'node:child_process'
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC_HOST = join(ROOT, 'src', 'host')
const LIB = join(ROOT, 'lib')
const LIB_HOST = join(LIB, 'host')

const args = new Set(process.argv.slice(2))
const skipEmbed = args.has('--skip-embed')
const skipClient = args.has('--skip-client')

function run(command, argv, cwd = ROOT) {
  const isWindows = process.platform === 'win32'
  const file = isWindows ? 'cmd.exe' : command
  const finalArgv = isWindows ? ['/c', command, ...argv] : argv
  execFileSync(file, finalArgv, { cwd, stdio: 'inherit' })
}

console.log('=== host half: src/host/*.js -> lib/host/*.js (+ lib/index.js) ===')
if (!existsSync(SRC_HOST)) {
  console.error('build: src/host is missing')
  process.exit(1)
}
mkdirSync(LIB_HOST, { recursive: true })

const sources = readdirSync(SRC_HOST).filter((name) => name.endsWith('.js'))
if (!sources.includes('index.js')) {
  console.error('build: src/host/index.js is missing')
  process.exit(1)
}

// Prune first: a module removed from src must not survive in lib.
let pruned = 0
for (const name of readdirSync(LIB_HOST)) {
  if (!name.endsWith('.js')) continue
  if (sources.includes(name)) continue
  rmSync(join(LIB_HOST, name))
  pruned += 1
}
for (const name of sources) {
  cpSync(join(SRC_HOST, name), join(LIB_HOST, name))
}

/**
 * `lib/index.js` is GENERATED, not copied.
 *
 * The package entry has to sit at `lib/index.js` (that is what `main` and the
 * `exports` map point at), while the host modules live in `lib/host/`. Copying
 * `src/host/index.js` up a level would leave its `./clip-id.js` imports pointing
 * at files that are not there — a mistake that only shows up when the plugin is
 * loaded. A one-line re-export cannot have that problem.
 */
const ENTRY = `/**
 * Generated by scripts/build.mjs. Do not edit — edit src/host/index.js.
 *
 * The host half lives in ./host/ so that each collaborator is its own module;
 * this file exists because \`main\` and the \`exports\` map point at lib/index.js.
 */
export { apply, name, inject } from './host/index.js'
`
writeFileSync(join(LIB, 'index.js'), ENTRY, 'utf8')
console.log(`host: copied ${String(sources.length)} module(s), pruned ${String(pruned)}, wrote lib/index.js shim`)

if (!skipEmbed) {
  console.log('=== built-in clips: embedding media/*.mp4 as base64 ===')
  run('node', ['scripts/embed-clips.mjs'])
}

if (!skipClient) {
  console.log('=== browser half: tsdown (lib/client.js) ===')
  run('npm', ['run', 'build:client'])
}

const required = [
  join(LIB, 'index.js'),
  join(LIB_HOST, 'clip-registry.js'),
  join(LIB_HOST, 'media-server.js'),
  join(LIB, 'client.js'),
  join(LIB, 'clips.meta.js'),
  join(LIB, 'clips.data.js'),
]
const missing = required.filter((p) => !existsSync(p))
if (missing.length > 0) {
  console.error('build: missing artifact(s):')
  for (const p of missing) console.error('  ' + p.slice(ROOT.length + 1))
  process.exit(1)
}

// Record what was built, so "is lib current?" is answerable without guessing.
const manifest = {
  builtAt: new Date().toISOString(),
  host: sources.map((name) => name),
  clientBundleBytes: readFileSync(join(LIB, 'client.js')).length,
}
writeFileSync(join(LIB, '.build-manifest.json'), JSON.stringify(manifest, null, 2) + '\n', 'utf8')

console.log('=== Build complete ===')
